### ISSUE TITLE
File size too large to be used as a template

### ISSUE THREAD

**Issue by donbale** [psmathur/fastai2-vision-app#1]
Thank you for this which I've successfully deployed locally: Just a heads up really as I was unable to use as a github template due to files being larger that 10Mb. I think its just because you've done a push with your model included and it wasn't included in a .gitignore file. Thanks for your work again.

**Comment by pankajarm** [comment]
Thanks for pointing that out Chris, I will update .gitignore accordingly
and push updates sometime today. Take care.

**Comment by donbale** [comment]
No problem

**Comment by pankajarm** [comment]
Ok, I have removed .pkl file so this repo can be used as github template, and it wasn't earlier as you mentioned due to size restrictions of 10 MB. Apparently, .gitignore didn't work. Look like, It is an expected behavior as mentioned here => https://github.com/education/classroom/issues/2521

Please try and let me know , if you still have issues. Again, thanks for reporting this appreciated.
